### ISSUE TITLE
Start with script?

### ISSUE THREAD

**Issue by zachcp** [ikappaki/basilisp-blender#1]
Hi @ikappaki ,

This is a great tool. Do you know of a way that I can invoke blender and initiation the repl via a script? The following yields operation not permitted errors.

```sh
/Applications/Blender.app/Contents/MacOS/Blender --python scripts/blender_interop/start_basilisp_nrepl.py
```

```python
import sys
import os
from basilisp_blender.nrepl import server_start

def start_nrepl_server():
    project_root = os.getcwd()  # Or specify your project root path
    nrepl_port_file = os.path.join(project_root, ".nrepl-port")
    shutdown_fn = server_start(nrepl_port_filepath=nrepl_port_file)
    print(f"nREPL server started. Port file: {nrepl_port_file}")
    return shutdown_fn

shutdown_fn = start_nrepl_server()

```

**Comment by zachcp** [comment]
So it seems if I run Blender and enter the commands in the python console theres no issue. So I'm guessing that blender is launched with the permissions level of the user that invokes it.

**Comment by jasalt** [comment]
@zachcp On Linux here and following https://docs.blender.org/manual/en/latest/advanced/command_line/arguments.html#command-line-args-python-options, and repo readme, this seems to work:

```
./blender --python-expr "from basilisp_blender.nrepl import server_start; shutdown_fn = server_start(port=8889);"
```

Also if you want it as script file, run `./blender --python /path/to/start_nrepl.py` which includes following copied from repo readme:
```
from basilisp_blender.nrepl import server_start
shutdown_fn = server_start(port=8889)
```

Exploring how to run Basilisp `.lpy` script files while starting from command line though, I guess the file should be called with the `eval_file` wrapper command.

**Comment by zachcp** [comment]
I am on MacOs and I am definitely hitting a set of permission issues when running.  Its not generic as I can run other code - but I think Basilisp has a compilation step which writes files and the App has protected write.

```
# works fine
/Applications/Blender.app/Contents/MacOS/Blender --python-expr "print(1 + 1)"
# permissions issues
/Applications/Blender.app/Contents/MacOS/Blender --python-expr "from basilisp_blender.nrepl import server_start; shutdown_fn = server_start(port=8889);"
```

I do really like the `.nrepl-port` file - and it would be great to have a single command load up Blender with a REPL AND connect to it on the editor side...

**Comment by zachcp** [comment]
Answer is [here](https://docs.blender.org/api/current/info_tips_and_tricks.html). I deleted the install python directory and am using my own.  Maybe when Blender is installed on Linux it uses the system python and you don't get this problem.

```md

# Bundled Python & Extensions

The Blender releases distributed from blender.org include a complete Python installation on all platforms, this has the disadvantage that any extensions you have installed on your system’s Python environment will not be found by Blender.

There are two ways to work around this:

- Remove Blender Python subdirectory, Blender will then fallback on the system’s Python and use that instead.
Depending on your platform, you may need to explicitly reference the location of your Python installation using the PYTHONPATH environment variable, e.g:

`PYTHONPATH=/usr/lib/python3.7 ./blender --python-use-system-env`


```
